# Generated by Django 3.2.8 on 2021-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='default_actors.jpeg', upload_to='pictures'),
        ),
    ]
